//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDemoProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DemoProjectEntitiescomplaint : DbContext
    {
        public DemoProjectEntitiescomplaint()
            : base("name=DemoProjectEntitiescomplaint")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblComplaint_Type> tblComplaint_Type { get; set; }
        public virtual DbSet<tblComplaintUser> tblComplaintUsers { get; set; }
    }
}
