//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDemoProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComplaint_Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblComplaint_Type()
        {
            this.tblComplaintUsers = new HashSet<tblComplaintUser>();
        }
    
        public int ComplaintId { get; set; }
        public string ComplaintName { get; set; }
        public Nullable<int> ComplaintCriticality { get; set; }
        public string ForwardPerson { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblComplaintUser> tblComplaintUsers { get; set; }
    }
}
