//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDemoProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComplaintUser
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Complaint { get; set; }
        public Nullable<int> ComplaintId { get; set; }
        public string ComplaintStatus { get; set; }
    
        public virtual tblComplaint_Type tblComplaint_Type { get; set; }
    }
}
